// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirebnech

// Injectors from wire.go:

// InitializeApp shows how Wire stitches dependencies together at compile time.
func InitializeApp(cfg *Config) *App {
	db := NewDB(cfg)
	redis := NewRedis(cfg)
	app := &App{
		DB:    db,
		Redis: redis,
	}
	return app
}
